[phases.setup]
cmds = [
  "apt-get update",
  "apt-get install -y libpq-dev nodejs curl git"
]

[phases.install]
cmds = ["bundle install"]

[phases.build]
cmds = ["bundle exec rails assets:precompile"]

[start]
cmd = "bundle exec rails server -b 0.0.0.0 -p $PORT"
